### PR TITLE
Proposed tweaks for pipeline via MKDocs

### PR DESCRIPTION
**Pull request by louh**
I'll talk about this in more detail at the next meeting, but in summary:

- Add a top-level heading for the entire page
- Rename file name so that the url schema could be `/metro-extracts/walkthrough/` instead of ` /metro-extracts/metro-extracts-walkthrough/`
- Images are referred to relative to this current folder

### CODE REVIEW

**Comment by rmglennon** [comment]
Thanks, @louh. Think I got these suggestions installed when I merged into master my own file with a bunch of updates based on feedback (from @IndyHurt).

**Comment by rmglennon** [comment]
Please reopen if I missed something that should have been merged manually (git was being a pain here to sort the changes)!

**Comment by louh** [comment]
Got it, thanks for checking! Did you try to do a diff or were you just eyeballing changes? I rebased my branch on yours, to double check, and you definitely caught everything.

**Comment by rmglennon** [comment]
Great! I did a diff and some eye-balling and more command-line merging than I could stand (good practice). Thanks for the updates.

**Pull request closed without merging**
